"""
fan_technical_drawing.py
--------------------------
Generates a dimensioned 2D DXF technical drawing (front view + side view)
of the axial fan, matching standard engineering-sheet layout: front view
shows the square mounting frame, casing circle, and blades visible inside
the hub ring; side view shows casing depth/profile. Diameter and length
dimensions are added as real DXF lines + text.

Pure 2D drafting via ezdxf - independent of the FreeCAD 3D generator
(blade_cad_generator.py). Run with plain python (ezdxf only, no FreeCAD
needed):
    pip install ezdxf
    python fan_technical_drawing.py

NOTE ON SCOPE: this reproduces the dimensioned front/side ORTHOGRAPHIC
views only. The reference sheet's isometric pictorial view and the
photorealistic motor housing render are hand-illustrated line art, not
something derivable from parametric dimensions - they are not included.
"""
from __future__ import annotations
import math
import ezdxf
from ezdxf.enums import TextEntityAlignment


def _dim_h(msp, x1, x2, y, offset=0):
    """Real horizontal linear DIMENSION entity - arrows/extension lines/
    text are auto-generated by the dimension style, not hand-drawn."""
    dim = msp.add_linear_dim(
        base=(( x1 + x2) / 2, y + offset), p1=(x1, y), p2=(x2, y),
        dimstyle="EZDXF", dxfattribs={"layer": "Dim"},
    )
    dim.render()


def _dim_v(msp, y1, y2, x, offset=0):
    """Real vertical linear DIMENSION entity."""
    dim = msp.add_linear_dim(
        base=(x + offset, (y1 + y2) / 2), p1=(x, y1), p2=(x, y2),
        angle=90, dimstyle="EZDXF", dxfattribs={"layer": "Dim"},
    )
    dim.render()


def _draw_blade(msp, cx, cy, hub_r, tip_r, width_deg, angle_deg, sweep_deg=18, layer="Geometry"):
    """Curved sickle-shaped blade (leading edge straight-ish radial,
    trailing edge swept back by sweep_deg) built from arcs, matching the
    curved-vane look of the reference drawing instead of a flat trapezoid."""
    a_lead = math.radians(angle_deg - width_deg / 2)
    a_trail_hub = math.radians(angle_deg + width_deg / 2)
    a_trail_tip = math.radians(angle_deg + width_deg / 2 + sweep_deg)

    n = 8
    pts = []
    # leading edge: hub -> tip, nearly radial
    for i in range(n + 1):
        t = i / n
        r = hub_r + t * (tip_r - hub_r)
        a = a_lead + t * math.radians(2)
        pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))
    # trailing edge: tip -> hub, swept back (curved)
    for i in range(n + 1):
        t = i / n
        r = tip_r - t * (tip_r - hub_r)
        a = a_trail_tip - t * (a_trail_tip - a_trail_hub)
        pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))
    pts.append(pts[0])
    msp.add_lwpolyline(pts, dxfattribs={"layer": layer})


def generate_fan_drawing(dims_mm: dict, output_path: str) -> str:
    fan_d = dims_mm["FanDiameterMm"]
    hub_d = dims_mm["HubDiameterMm"]
    blade_count = int(dims_mm["BladeCount"])
    casing_len = dims_mm["CasingLengthMm"]
    frame_size = dims_mm.get("MountingFrameSizeMm", fan_d * 1.25)
    corner_r = dims_mm.get("FrameCornerRadiusMm", frame_size * 0.12)
    wall_t = dims_mm.get("WallThicknessMm", 3.0)

    fan_r = fan_d / 2.0
    hub_r = hub_d / 2.0
    casing_outer_r = fan_r + wall_t

    doc = ezdxf.new("R2000", setup=True)
    msp = doc.modelspace()
    for name, color in [("Geometry", 7), ("Dim", 1), ("Text", 3)]:
        doc.layers.add(name, color=color)
    # Arrow/text size scaled to the drawing (mm-scale geometry) - default
    # EZDXF dimstyle arrows are far too small at this scale otherwise.
    dimstyle = doc.dimstyles.get("EZDXF")
    dimstyle.dxf.dimasz = 8
    dimstyle.dxf.dimtxt = 8
    dimstyle.dxf.dimexe = 3
    dimstyle.dxf.dimexo = 3

    # ---------------- FRONT VIEW (left side of sheet) ----------------
    fx, fy = 0, 0  # front view center

    half = frame_size / 2.0
    # square mounting frame with rounded corners
    pts = [
        (fx - half + corner_r, fy - half), (fx + half - corner_r, fy - half),
        (fx + half, fy - half + corner_r), (fx + half, fy + half - corner_r),
        (fx + half - corner_r, fy + half), (fx - half + corner_r, fy + half),
        (fx - half, fy + half - corner_r), (fx - half, fy - half + corner_r),
    ]
    pts.append(pts[0])
    msp.add_lwpolyline(pts, dxfattribs={"layer": "Geometry"})

    msp.add_circle((fx, fy), casing_outer_r, dxfattribs={"layer": "Geometry"})
    msp.add_circle((fx, fy), hub_r, dxfattribs={"layer": "Geometry"})

    blade_width_deg = 360.0 / blade_count * 0.55
    for k in range(blade_count):
        ang = 360.0 * k / blade_count
        _draw_blade(msp, fx, fy, hub_r, casing_outer_r * 0.92, blade_width_deg, ang)

    # dimensions: casing OD, hub bore, frame width
    _dim_v(msp, fy - casing_outer_r, fy + casing_outer_r, fx - half, offset=-30)
    _dim_h(msp, fx - hub_r, fx + hub_r, fy - casing_outer_r, offset=-25)
    _dim_h(msp, fx - half, fx + half, fy - half, offset=-40)

    msp.add_text("FRONT VIEW", dxfattribs={"layer": "Text", "height": 10}).set_placement(
        (fx - half, fy - half - 70), align=TextEntityAlignment.LEFT)

    # ---------------- SIDE VIEW (right side of sheet) ----------------
    sx = frame_size + 150  # side view offset to the right
    sy = 0

    # casing profile: rectangle (length x OD), inlet/outlet flange rings
    msp.add_lwpolyline([
        (sx, sy - casing_outer_r), (sx + casing_len, sy - casing_outer_r),
        (sx + casing_len, sy + casing_outer_r), (sx, sy + casing_outer_r),
        (sx, sy - casing_outer_r),
    ], dxfattribs={"layer": "Geometry"})

    flange_w = dims_mm.get("FlangeWidthMm", 20.0)
    for fx_edge in (sx, sx + casing_len):
        msp.add_line((fx_edge, sy - casing_outer_r - flange_w),
                     (fx_edge, sy + casing_outer_r + flange_w),
                     dxfattribs={"layer": "Geometry"})

    # shaft centerline
    msp.add_line((sx - 20, sy), (sx + casing_len + 20, sy),
                 dxfattribs={"layer": "Geometry", "linetype": "CONTINUOUS"})

    _dim_v(msp, sy - casing_outer_r, sy + casing_outer_r, sx + casing_len, offset=40)
    _dim_h(msp, sx, sx + casing_len, sy - casing_outer_r - flange_w, offset=-25)

    msp.add_text("SIDE VIEW", dxfattribs={"layer": "Text", "height": 10}).set_placement(
        (sx, sy - casing_outer_r - flange_w - 60), align=TextEntityAlignment.LEFT)

    msp.add_text(f"Axial Fan - {blade_count} blades - Scale 1:1 (mm)",
                 dxfattribs={"layer": "Text", "height": 8}).set_placement(
        (fx - half, fy - half - 100), align=TextEntityAlignment.LEFT)

    doc.saveas(output_path)
    print(f"Exported technical drawing: {output_path}")
    return output_path


if __name__ == "__main__":
    sample_dims = {
        "FanDiameterMm": 400,
        "HubDiameterMm": 240,
        "BladeCount": 6,
        "CasingLengthMm": 114,
        "MountingFrameSizeMm": 507,
        "WallThicknessMm": 3,
        "FlangeWidthMm": 15,
    }
    generate_fan_drawing(sample_dims, "fan_technical_drawing.dxf")